name: CD

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FOLDER_NAME: /Users/fanzru/frontend/frontend-evoting/scripts
    steps:
      - uses: actions/checkout@v2
      - name: Preparing to deploy to production 🚀🤘
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          script: |
            cd ~/frontend/frontend-evoting/scripts
            chmod +x deploy.sh
            ./deploy.sh